version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=DDD_DB;Username=Ebrahem;Password=Ebrahem0123
      - Redis__Configuration=redis:6379
    networks:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: DDD_DB
      POSTGRES_USER: Ebrahem
      POSTGRES_PASSWORD: Ebrahem0123
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

networks:
  backend:
    driver: bridge